### ISSUE TITLE
OAuth example InvalidCastException on Android

### ISSUE THREAD

**Issue by codehtmai** [Esri/arcgis-runtime-samples-dotnet#511]
Hello,

When running the OAuth example on Android, I receive an InvalidCastException for [line 154](https://github.com/Esri/arcgis-runtime-samples-dotnet/blob/a61046c0432110bc45f6597a9ea0fcbcf430f323/src/Forms/Shared/Samples/Security/OAuth/OAuth.xaml.cs#L154), `Activity activity = (Activity)Android.App.Application.Context;`. 
I'm just getting started with Xamarin Forms/Android development, so I'm not too sure how to fix this. Any help would be appreciated!

**Comment by ThadT** [comment]
Hi @codehtmai 
I gave this a look and ran into similar problems. It's interesting, because the `Author and save a map` sample uses the same code and doesn't throw the exception.
After looking into it further, I found another way to get the `Context` that seems to work more consistently. I'll try to get this fix into the sample viewer soon, but I've described it here in case you want to give it a try.

1) Add the following property to the `MainActivity` class (`MainActivity.cs` file in the `ArcGISRuntime.Xamarin.Forms.Android` project).
```csharp
internal static MainActivity Instance { get; private set; }
```
2) Set the value of the `Instance` property in the `OnCreate` function.
```csharp
Instance = this;
```
Here's what the `MainActivity` class should look like:
```csharp
public class MainActivity : Xamarin.Forms.Platform.Android.FormsApplicationActivity
{
    internal static MainActivity Instance { get; private set; }

    protected override void OnCreate (Bundle bundle)
	{
		base.OnCreate (bundle);

                Instance = this;

                Xamarin.Forms.Forms.Init (this, bundle);
		LoadApplication (new App ());
	}
}
```

3) On line you mentioned in the `OAuth` sample (154), change it to get the context from `MainActivity':
```csharp
Activity activity = (Activity)ArcGISRuntime.Droid.MainActivity.Instance;
```

Feel free to contact me directly if you have further problems getting this to work: ttilton@esri.com

**Comment by codehtmai** [comment]
Thanks for your quick reply. I also ended up having some luck with the [Current Activity Plugin](https://github.com/jamesmontemagno/CurrentActivityPlugin), but your solution doesn't require another dependency.
