### ISSUE TITLE
fail to open .gpk file by local server

### ISSUE THREAD

**Issue by XiaoZhong233** [Esri/arcgis-runtime-samples-dotnet#567]
hello,i am trying to open .gpk file in vs2017 which has equipped arcgisLocalServer
here is my code

>  private void initGPService()
        {
            //test
            mainWindow.test1.Click += async (s, e) =>
            {
                LocalFeatureService featureService = new LocalFeatureService(@"E:\Desktop\学习\大三上\GIS课程设计\gpk\ClustersOutliers.gpk");
                featureService.StatusChanged += (svc, args) =>
                {
                    if (args.Status == LocalServerStatus.Started)
                    {
                        mainWindow.operationStatus.Text = "运行服务中";
                        //获取URI
                        var featureServiceUrl = (svc as LocalFeatureService).Url.AbsoluteUri;
                        // 创建GP Task
                        ServiceFeatureTable localServiceTable = new ServiceFeatureTable(new Uri(featureServiceUrl));
                        //获取图层
                        FeatureLayer featureLyr = new FeatureLayer(localServiceTable);
                        //加入图层
                        mainWindow.MyMapView.Map.OperationalLayers.Add(featureLyr);
                        // TODO:构造参数...运行等等..
                    }else if(args.Status == LocalServerStatus.Failed)
                    {
                        MessageBox.Show("failed");
                    }
                };
                // 开始运行服务
                await featureService.StartAsync();
            };
        }

 Status is Failed, and an exception is throwed at ` await featureService.StartAsync()`,which is 

> Esri.ArcGISRuntime.Http.ArcGISWebException:“Failed to create service clustersoutliers MapServer. Service failed to initialize: IObjectConstruct::Construct (MapServer) hr=0x80043000 (ErrorInfo did not include a description)”

errorCode is 500.

i don't know why,I should be grateful if you would kindly consider my issue.

**Comment by ThadT** [comment]
Hi Xiao,
It looks like the problem is that you are initializing a `LocalFeatureService` instead of a `LocalGeoprocessingService`. I think making an edit like the one below will work:
```
LocalGeoprocessingService gpService = new LocalGeoprocessingService(@"E:\Desktop\学习\大三上\GIS课程设计\gpk\ClustersOutliers.gpk");
```
You'll find a description and example of running a local geoprocessing service in the [Local Server guide topic](https://developers.arcgis.com/net/latest/wpf/guide/local-server.htm#ESRI_SECTION1_AE6F43DD53224D068D0A7FAFE4F9A205). There is also a [Local Server geoprocessing sample](https://developers.arcgis.com/net/latest/wpf/sample-code/localservergeoprocessing.htm) that you might find useful.

**Comment by XiaoZhong233** [comment]
thank for your reply, i have used `LocalGeoprocessingService` . but it doesn't work

>           gpServiceUrl = @"E:\Desktop\学习\大三上\GIS课程设计\gpk\ClustersOutliers.gpk";
            _gpService = new LocalGeoprocessingService(gpServiceUrl, GeoprocessingServiceType.AsynchronousSubmitWithMapServiceResult);
            // Try to start the service
            try
            {
                // Start the service
                await _gpService.StartAsync();
            }
            catch (Exception)
            {
                MessageBox.Show("geoprocessing service failed to start.");
            }

it still alert that service failed to start and throw the ArcGISWebException.

**Comment by ThadT** [comment]
I ran the code below successfully (with a different geoprocessing package). Maybe the problem is with the gpk?

```
    string gpServiceUrl = @"C:\Temp\学习\大三上\GIS课程设计\gpk\message-in-a-bottle.gpk"; 
    gpService = new LocalGeoprocessingService(gpServiceUrl, GeoprocessingServiceType.AsynchronousSubmitWithMapServiceResult);
    await gpService.StartAsync();
```

I suggest you ask this question on GeoNet and see if anyone in the [ArcGIS Runtime SDK for .NET community](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net) has experienced the same problem. Please include your code and, if possible, the full exception message and call stack.

**Comment by XiaoZhong233** [comment]
the gpk file is generated by arcgis desktop 10.2 , is there something wrong in my gpk file? how can i get the proper gpk file?

**Comment by mbranscomb** [comment]
@XiaoZhong233 

This repo is for issues concerning Samples for ArcGIS Runtime SDK for .NET. Please post general questions related to development with the SDK in https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net.

When submitting questions in Geonet, you will have the most success if you include your code, the full exception message, and call stack.

**Comment by TragedyGitHub** [comment]
I've the problem too, my classmate.
