### ISSUE TITLE
OfflineMapBook .NET Core  Failed

### ISSUE THREAD

**Issue by sc9196** [Esri/arcgis-runtime-samples-dotnet#749]
Hi.  I just tried downloading this sln and loading it in VS.  I see you added a project a couple of days ago.  That project fails to load.   Are there some supporting files that are missing?

Here is the error message:
C:\Users\sc9196\Downloads\mapbook-wpf-master(2)\mapbook-wpf-master\OfflineMapBook\OfflineMapBook\OfflineMapBook (.NET Core).csproj : error  : Project file is incomplete. Expected imports are missing.

Thanks,
Steve Czajkowski

**Comment by nCastle1** [comment]
Hi, 

Which version of Visual Studio are you using?

**Comment by sc9196** [comment]
Nathan,   Thanks.  Using VS Community 2017
Version 15.9.19
Steve

**Comment by nCastle1** [comment]
I confirmed that Visual Studio 2017 doesn't support .NET Core 3, so that project won't be able to load. You should be able to use the .NET Framework version even without the .NET Core project loaded. 

I'll update the solution to not reference the .NET Core project for now.

If you'd like to give the .NET Core project a try, VS Community 2019 should be a free download.

**Comment by sc9196** [comment]
Thanks Nathan.  Will appreciate it.

**Comment by nCastle1** [comment]
@sc9196 I've merged a PR that adds a solution for 2017 support - ` 	OfflineMapBook.2017Compat.sln`. Let me know if that solution works for you. Thanks!

**Comment by sc9196** [comment]
Nathan,   Thanks so much.  I took your suggestion and installed vs 2019.   It worked fine.
Steve
